spring:
  application:
    name: KognitaBackend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kognita}
    username: ${SPRING_DATASOURCE_USERNAME:kognita}
    password: ${SPRING_DATASOURCE_PASSWORD:kognita123}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}
